### ISSUE TITLE
lille katt test

### ISSUE THREAD

**Issue by lissch** [cybear/vaggvisor.org#20]
---
categories: ['Astrid Lindgren','Georg Riedel']
title: 'Lille katt'
spotify_id: 3l6DIT1Es47FMhwMV7c0rl
youtube_id: fFh9WleBkRk
---

Lille katt, lille katt  
Lille söte katta  
Vet du att, vet du att  
De blir mörkt om natta

Lille gris, lille gris  
Lille söte grisen  
Om du frys, om du frys  
Så gör eld i spisen

Lille ko, lille ko  
Lille söte koa  
De va ho, de va ho  
Ho som sket på broa

Lille mor, lille mor  
Lille söte mora  
Ho fick skor, ho fick skor  
Men dom va för stora

Lille far, lille far  
Lille söte faren  
En sån karl, en sån karl  
De e tur vi har'en

Lille ja, lille ja  
Lille söte Ida  
Ja vill ha, ja vill ha  
Rotemos till midda'

Text: Astrid Lindgren, musik: Georg Riedel

**Comment by lissch** [comment]
--- 
categories: ['Margit Holmberg'] 
title: 'Trollmors vaggvisa' 
spotify_id: 2tu5QdvwqjQikupzaJRLV7
youtube_id: QZOBnKYXEU0
---  


När trollmor har lagt de elva små trollen
och bundit fast dem i svansen,
då sjunger hon sakta för elva små trollen
de vackraste ord hon känner
 
Ho aj aj aj aj buff
ho aj aj aj aj buff
ho aj aj aj aj buff buff
Ho aj aj aj aj buff

Text och musik: Margit Holmberg

**Comment by lissch** [comment]
--- 
categories: ['Johannes Brahms', 'Alice Tegnér'] 
title: 'Nu i ro slumra in' 
spotify_id: 7q27pClAgCpufAA7v2ZsCi
youtube_id: pzlLaYAUnhU
---  

Nu i ro, slumra in, i bädden så fin, 
som blomman på äng, i en gungande säng. 
Och Guds änglar de små, breda vingarna ut, 
och för barnet till ro, tills natten är slut. 

Nu i ro, slumra in, lilla älsklingen min, 
ner i kudden dig göm, i din rosiga dröm. 
Tills du väcks lilla vän, nästa morgon igen, 
tills du väcks lilla vän, nästa morgon igen.

Text: Alice Tegnér, musik: Johannes Brahms,

**Comment by lissch** [comment]
--- 
categories: ['Alice Tegnér'] 
title: 'Dansa min docka' 
spotify_id: 2vsUU0Dxp5eokYv1mRsTaa
youtube_id: dGDgrmJy3Ng
---  

Dansa min docka, medan du är unger,
när du blir gammal, blir du så tunger.

Dansa min docka, medan du är unger,
när du blir gammal, blir du tung.

Musik och text: Alice Tegnér

**Comment by lissch** [comment]
--- 
categories: ['Alice Tegnér'] 
title: 'Vart ska du gå, min lilla flicka' 
spotify_id: 3UiyOwYrZ17SxVg3mWmzdX
youtube_id: r5ItjYSBEOk
---  

Vart ska du gå, min lilla flicka?
Jo, jag ska gå och hämta dricka
Åt vem då du lilla tärna?
Åt vår get som heter Stjärna
Får jag följa med?
Får jag följa med?
Ja det får du gärna
Får jag följa med?
Får jag följa med?
Ja det får du gärna. 

Musik och text: Alice Tegnér

**Comment by lissch** [comment]
--- 
categories: ['Alice Tegnér'] 
title: 'Lilla Lasse' 
spotify_id: 32kXOV8n9qLWma0Oi3nyc6
youtube_id: qatuErhps2U
---  

Lilla Lasse går och gråter,
borta är hans fiskarebåt.
Gråt inte, Lasse lilla,
båten ligger i vassen stilla
full med gäddor och braxen.

Musik och text: Alice Tegnér

**Comment by lissch** [comment]
--- 
categories: ['Adolf Iwar Arwidsson'] 
title: 'Gåsa gåsa klinga 
spotify_id: 7wnUBSgbr62gQnagCVUDLL 
youtube_id: h7yL_WRJy6c
---  

Gåsa, gåsa klinga.
Län mig dina vingar.
Vart ska vi flyga?
Till rosende lund.
Där bor göken,
där gror löken,
där bygger svalan,
där är gott att vara.
Där sitta gummor,
och spela på gulltrummor.
Där sitta gubbar,
och spela på gullstubbar.
Där sitta drängar,
och spela på gullsträngar.
Där sitta pigor,
och spela på gullgigor. 
Där sitta snälla barn och leka med gulläpplen.
Där sitter du och där sitter jag.

A.
Gåsa, gåsa klinge,
Får jag låna din vinge!
"Hvart skall du flyga!"
Jag skall flyga åt Wermeland,
Det är godt att vara!
Der gror löken,
Der gal göken!
Der sitter gubbe
Och stickar på guldstubbe.
Der sitta små barn och roa sig,
Med guldäpple och guldpära.

B.
Gåsa, gåsa klinga,
Låna mig dina vinga!
"Hwart skall du svina?"
Svinga till min faders gård,
Der är godt att vara!
Der sjunger svala,
Der sitta gubbar,
Sömma guldkuddar;
Der sitter litet barn och leker,
Med guldäpple, guldäpple!

Trad., nedtecknad av Adolf Iwar Arwidsson 1842

**Comment by lissch** [comment]
Byssan lull, koka kittelen full. 
Byssan är köket på skeppet.

**Comment by lissch** [comment]
B.
Gåsa, gåsa klinga,
Låna mig dina vinga!
"Hwart skall du svina?"
Svinga till min faders gård,

Misstag, det ska ju stå "Hwart skall du svinGa" såklart...

**Comment by lissch** [comment]
--- 
categories: ['Alice Tegnér'] 
title: 'Baka kaka' 
spotify_id: 1XYlU6n8xeZDyq1i2y3p9v
youtube_id: TJFnwUwbqw4
---  

Baka, baka kaka!
Vem ska kakan smaka?
Det ska far och det ska mor,
lilla syster, store bror.
Skall det bli till flera,
får vi baka mera.

Mjöla, mjöla, pricka,
kakan i ugnen sticka.
Låt oss baka kakan stor:
Mamma säger att hon tror
liten sparv behöver
smulor som blir över.


Musik & text: Alice Tegnér

**Comment by lissch** [comment]
--- 
categories: ['Hoffmann von Fallersleben'] 
title: 'Alla fåglar kommit re'n' 
spotify_id: 2PEfDtPJWGdMiVIPzlT7OV
youtube_id: Rg2srOhxdlc
---  

1. Alla fåglar kommit re'n,
vårens glada gäster. 
Vilken fröjd i solens sken,
vilka sångarfester! 
Lärkan drillar högt i sky,
våren är ju evigt ny. 
Jordens högtid börjar gry, 
sprider fröjd åt alla. 

2. Vilken glädje, hör, ja hör! 
Nätt och lätt de trippa. 
Gök och trast och siskors kör
väcka upp var sippa. 
Oss de önska sommarfröjd, 
jubla högt i himmelshöjd. 
Skogen står så grön, och fröjd 
ljuder från var klippa.

3. Trast och fink och siskor små 
sjunga glatt ur snåren. 
Göken räknar i sin vrå 
dagarna och åren. 
Skogen står så grön och ljus, 
gungar lätt i sunnansus. 
Duvan i sitt gröna hus 
fröjdar sig åt våren.

4. Vad de oss förkunna må, 
lägga vi på minne. 
Mulna dar nog återstå, 
töcken för vårt sinne. 
Vi som luftens fåglar små
i vårt inre gläds ändå, 
han som våren skänkt också
lyser upp därinne.  

Original på tyska: Hoffmann von Fallersleben

**Comment by lissch** [comment]
--- 
categories: ['Carl Michael Bellman'] 
title: 'Björnen sover' 
spotify_id: 0JGcH6rf6HXjjMwrifPKQ0
youtube_id: n5dGWfcWO9w
---  

Björnen sover, björnen sover
i sitt lugna bo.
Han är inte farlig
bara man är varlig
Men man kan dock,
men man kan dock
honom aldrig tro.


Musik: kanske Carl Michael Bellman, text: kanske Anne-Marie och Bengt Olov Engström

**Comment by lissch** [comment]
--- 
categories: ['Georg Riedel'] 
title: 'Lilla ungen min' 
spotify_id: 6Vtx810nsIlLPxTv3Tu8Oa
youtube_id: _YuNzAN0ORw
---  

Sov nu, lilla ungen min.
Sätt i munnen tummen din.
Lent som siden är ditt skinn,
lilla ungen min.

Musik och text: Georg Riedel

**Comment by lissch** [comment]
märker att jag varit inkonsekvent med "text och musik". lovar att hålla mig till en och samma hädanefter, haha

**Comment by lissch** [comment]
--- 
categories: ['Astrid Lindgren', 'Georg Riedel'] 
title: 'Grisevisan (Ibland går jag runt och trallar)' 
spotify_id: 3i4pziVywtyXWp3KNi9kLP
youtube_id: UnBYy7HMMQs
---  

Ibland går jag runt och trallar
Jag trallar för mig själv
och för min lilla gris
och grisen blir så glad
så han hoppar när jag trallar
så där på mitt eget lilla vis.
 
Ibland går jag runt och visslar
Jag visslar för mig själv
och för min lilla gris
och grisen blir så glad
så han grymtar när jag visslar
så där på mitt eget lilla vis.
 
Ibland går jag runt och tjoar
Jag tjoar för mig själv
och för min lilla gris
och grisen blir så glad
så han skuttar när jag tjoar
så där på mitt eget lilla vis.
 
Ibland går jag runt och trummar
Jag trummar för mig själv
och för min lilla gris
och grisen blir så glad
så han dansar när jag trummar
så där på mitt eget lilla vis.
 
Ibland går jag runt och tjurar
och tiger och är arg
på alla sätt och vis
och då blir grisen sur
så det osar och det säger han
ifrån på sitt grisavis.
 
Då trallar jag och visslar
och tjoar och trummar
och muntrar upp min gris
För han blir ju så glad
när det låter på sådär
många roliga små sätt och vis.


Text: Astrid Lindgren, musik: Georg Riedel

**Comment by cybear** [comment]
@lissch Ingen fara, jag hade rättat till svinga :)

**Comment by lissch** [comment]
--- 
categories: ['Ingela "Pling" Forsman', 'Hans Matthison-Hansen', 'Margrethe Munthe'] 
title: 'Vi har en tulta med ögon blå' 
spotify_id: 5JE3cxqGynyRFJnZUZznuT
youtube_id: v=3SPCwxFGI0k
---  

Vi har en tulta med ögon blå
Med silkeshår och med öron små
Och mitt i mitten
Den lilla tippen
Så stor som så
Så mjuk som sammet är hennes kind
Och hon är gullig och tjock och trind
Med pyttehänder
Och två små tänder
I munnen sin
Och hon kan bita i sina tår
Och hon kan snurra så fort det går
Och hon kan äta
Sen får du mäta
Hur högt hon når
Och Tultan rufsar i pappas hår
Och ler och vinkar åt den som går
Och bakar kaka
Och vå får smaka
På allt hon får
I baljan plaskar hon, må du tro
Sen vill hon sova i lugn och ro
Som gräddtårtsbiten
Är tultaliten
Vad hon är go!


Text: Ingela "Pling" Forsman och Hans Matthison-Hansen, musik: Margrethe Munthe

**Comment by lissch** [comment]
--- 
categories: ['Astrid Lindgren', 'Georg Riedel'] 
title: 'När mamma var liten' 
spotify_id: 3n8SCtfmtxcNy4WgALE7UJ
youtube_id: _7nOfH7ornM
---  

När mamma var liten, då var hon så rar 
och så tjock och så trind som en bulle
Och då sa hennes far att den ungen är rar, 
men hon ser inte ut som hon skulle

Tycker jag tycker jag tycker jag tycker jag, 
nej hon ser inte ut som hon skulle.

När mamma var liten då var hon så rar 
och så pigg som en ärta det var hon
Och då sa hennes far att den ungen är rar
men en tjock liten mage det har hon

Tycker jag tycker jag tycker jag tycker jag, 
ja en tjock liten mage det har hon.

När mamma var liten då var hon så rar
och så kvick som en kattunge var hon
Och då sa hennes far att den ungen är rar
men en märkvärdig näsa det har hon

Tycker jag tycker jag tycker jag tycker jag, 
ja en märkvärdig näsa det har hon.

När mamma var liten då var hon så rar 
och så snäll som en gullhöna var hon
Och då sa hennes far att den ungen är rar 
fastän konstiga öron det har hon
Tycker jag tycker jag tycker jag tycker jag
ena konstiga öron det har hon.

När mamma var liten och var så där rar
fast hon inte såg ut som hon skulle
Tänk då sa hennes far en sån unge jag har, 
hon är go som den goaste bulle.
Åh så söt och så fin och så rund och så rar, 
tänk så bra att hon blev som hon skulle.

Text: Astrid Lindgren, musik: Georg Riedel

**Comment by lissch** [comment]
--- 
categories: ['Jojje Wadenius'] 
title: 'Jag har en äng' 
spotify_id: 2qAORY53nNdgviJAnhKbHN
youtube_id: bS-xu7B9bno
---  

Jag har en äng, en grön och stor
jag har en äng med fyra kor
där göken sitter i en lund och gal
  
ko ko ko, ko ko ko, ko ko ko
Och grönskan står som en jättesal
  
Där dimman lättar, det blir dag
en äng med träd och gröna blad
Just så är min äng som doftar vår
  
ko ko ko, ko ko ko, ko ko ko
  
Där alla mina fartyg står
och finns det vind så seglar jag till andra fjärran länder
Mojnar det, blir lugnt nån dag
brukar jag ro med mina händer
  
ko ko ko, ko ko ko, ko ko ko
Na na na na na na na na

Jag har en äng, en grön och stor
jag har en äng med fyra kor
där göken sitter i en lund och gal
 
ko ko ko, ko ko ko, ko ko ko
Och grönskan står som en jättesal

Text och musik: Jojje Wadenius

**Comment by lissch** [comment]
--- 
categories: ['Nationalteatern'] 
title: 'Ylle (Jag är ett litet ylle)' 
spotify_id: 2U5yAQkzEMEe3visjpRLhj
youtube_id: uvgraB5uiKs
---  

Jag är ett litet ylle 
bom sickabom sickabombombom 
Med världens minsta nylle 
bom sickabom sickabombombom 
Jag leker i min yllegrop och yllar glada yllerop 
ylle ylle ylle på er yllihop  

Jag är så yllans liten 
bom sickabom sickabombombom 
fast inte i apiten 
bom sickabom sickabombombom 
Jag käkar en massa yllegarn 
och ett och annat ylleflarn 
ylle ylle ylle på er yllebarn  

Jag bor här mitt på bystan 
bom sickabom sickabombombom 
bland alla ylle nystan 
bom sickabom sickabombombom 
Här kryllar det av kryllingar 
och alla deras bryllingar 
ylle ylle ylle på er yllingar  

Nu kryper jag i sängen 
bom sickabom sickabombombom 
på mjuka ylle ängen 
bom sickabom sickabombombom 
En sömning ylle krumelur 
bör ofta ta en yllelur 
ylle ylle ylle på er ylledjur 


Text och musik:  Nationalteatern

**Comment by lissch** [comment]
--- 
categories: ['Traditionell'] 
title: 'Du skåning' 
spotify_id: 7aTZyFOAIhJ03QRZk2jI61
youtube_id: hyXtZhrYAQ4
---  

Du skåning, du skåning,
i morgon får du äta gröt
och doppa den i honung
så bliver den så söt
Och när jag säga stopp,
så får du hålla opp.
Tra lalalala lala lala
lala lala stopp.


Text och musik:  Traditionell

**Comment by lissch** [comment]
--- 
categories: ['Traditionell'] 
title: 'Kristallen den fina' 
spotify_id: 55zZ62m7LW3tZoIiMPg3pw
youtube_id: cllrNc--moc
---  

Kristallen den fina som solen månd’ skina
som stjärnorna blänka i skyn.
Jag känner en flicka i dygden den fina
en flicka i denna här byn.
Min vän, min vän och älskogsblomma!
Ack om vi kunde tillsammans komma
och jag vore vännen din.
och du allra kärestan min!
du ädela ros och förgyllande skrin.

Och om jag än fore till värdenes ände
så ropar mitt hjärta till dig.
Och om jag än fore till värdenes ände
så ropar mitt hjärta till dig.
Till dig, min vän och älskogsblomma!
Ack om vi kunde tillsammans komma
och jag vore vännen din.
och du allra kärestan min!
du ädela ros och förgyllande skrin.

Text och musik:  Traditionell

**Comment by lissch** [comment]
--- 
categories: ['Gullan Bornemark'] 
title: 'Är du vaken Lars' 
spotify_id: 6iFhC14wnrQk6JzRoXdDd7
youtube_id: _miBL7E3wd8
---  

Är du vaken Lars?
Är du vaken Lars?
Har du tvättat händerna, tvättat händerna?
Är du vaken Lars, e du vaken Lars?
och har du borstat, har du borstat tänderna?
Jag är vaken mor
Jag är vaken mor,
jag har tvättat händerna, tvättat händerna.
Jag är vaken mor, jag är vaken mor,
men jag glömde, men jag glömde tänderna!

Du är duktig Lars
Du är duktig Lars,
som har tvättat händerna, tvättat händerna!
Men hur kan du Lars, men hur kan du Lars,
men hur kan du glömma borsta tänderna?
Jag är duktig mor
Jag är duktig mor,
som har tvättat händerna, tvättat händerna.
Men jag luras, mor,
Men jag luras, mor!
Jag har borstat, jag har borstat tänderna!
Ha ha ha, det gjorde jag bra!
Ha ha ha, det gjorde jag bra!


Text och musik:  Gullan Bornemark

**Comment by cybear** [comment]
@lissch jag tror vi kan referera till denna listan vad gällande upphovsman för Ylle (och andra visor från nationalteatern) http://www.nationalteatern.nu/skivor/kalsipper.htm

**Comment by lissch** [comment]
Tackar!

**Comment by cybear** [comment]
(Jag har korrigerat denna redan)

**Comment by cybear** [comment]
@lissch För Traditionell, använd kategori "trad" (jag har korrigerat)

**Comment by lissch** [comment]
Ok!
