### ISSUE TITLE
En kulen natt

### ISSUE THREAD

**Issue by lissch** [cybear/vaggvisor.org#21]
--- 
categories: ['Anders Palm', 'Johan Stenström'] 
title: 'En kulen natt' 
spotify_id: 2guF6voX3pqejmmFU1EFnM
youtube_id: _miBL7E3wd8
---  

En kulen natt, natt, natt
min båt jag styrde
på havets vågade, vågade, våg
så skummet yrde.
Och vart jag sågade, sågade, såg
på havets vågade, vågade, våg
långt ner i djupetti, petti, pe
en fisk jag såg, och det var du…

Text och musik:  Anders Palm red., Johan Stenström red.

**Comment by cybear** [comment]
Fixed in a5df580e58290104ccd89dee19f093a3a9c56c9b
